# Generated by Django 4.1.3 on 2022-12-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postCategory',
        ),
        migrations.AddField(
            model_name='post',
            name='postCategory',
            field=models.CharField(choices=[('IT', 'Айти'), ('SP', 'Спорт'), ('CA', 'Машины'), ('POL', 'Политика')], default='IT', max_length=3),
        ),
    ]
