# Generated by Django 4.1.3 on 2022-12-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_post_postcategory_post_postcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postCategory',
            field=models.CharField(choices=[('IT', 'Айти'), ('SP', 'Спорт'), ('CA', 'Машины'), ('POL', 'Политика'), ('FM', 'Управление качесвом продуктов питания')], default='IT', max_length=3),
        ),
    ]
