# Generated by Django 4.1.3 on 2022-12-14 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='categoryThrough',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='postThrough',
            new_name='post',
        ),
    ]
