# Generated by Django 4.1.3 on 2022-12-15 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rename_categorythrough_postcategory_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='category',
            new_name='categoryT',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
